-- <autogenerated>
--   This file is generated from T4 template DeleteProcedure.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

CREATE PROCEDURE [dbo].[Foo_Delete]
    @Id INT 
AS
BEGIN
	DELETE FROM [dbo].[Foo] 
	WHERE
		[Id] = @Id	
END
