-- <autogenerated>
--   This file is generated from T4 template ListProcedure.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

CREATE PROCEDURE [dbo].[Foo_List]
    @PageIndex INT = 0,
	@PageQty INT = 20,
	@OrderBy  VARCHAR(100) = NULL,
	@SortDirection VARCHAR(4) = 'DESC',
	@TotalCount INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	if (@OrderBy IS NULL)
		SET @OrderBy = 'Id'

	if (@SortDirection IS NULL OR (@SortDirection <> 'ASC' AND @SortDirection <> 'DESC'))
		SET @SortDirection = 'DESC'

	SELECT @TotalCount = COUNT(*) FROM [dbo].[Foo] WITH (NOLOCK)
	--SELECT COUNT(*) FROM [dbo].[Foo] WITH (NOLOCK)

	DECLARE @offSet INT = IIF(@PageIndex < 0, 0, @PageIndex * @PageQty)
	
	IF (@PageQty > 0)
	BEGIN
		DECLARE @sql NVARCHAR(MAX) = 
		N'SELECT [Id],
        [LastUpdate],
        [Active],
        [OtherFlag],
        [FKFirstNotNull],
        [FKSecondNull],
        [FKThirdDefaultValue],
        [Labels] 
		FROM [dbo].[Foo] WITH (NOLOCK)
		ORDER BY ' + @OrderBy + ' ' + @SortDirection + '
		OFFSET @offSet ROWS
		FETCH NEXT @PageQty ROWS ONLY'

		DECLARE @paramArg NVARCHAR(MAX) = N'@offSet INT, @PageQty INT'
		EXEC sp_executesql @sql, @paramArg, @offSet, @PageQty
	END
	
END
