-- <autogenerated>
--   This file is generated from T4 template UpdateProcedure.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

CREATE PROCEDURE [dbo].[Foo_Update]
    @Id INT,
    @LastUpdate DATETIME,
    @Active BIT,
    @OtherFlag BIT,
    @FKFirstNotNull INT,
    @FKSecondNull INT,
    @FKThirdDefaultValue INT,
    @Labels VARCHAR(300) 
AS
BEGIN
	UPDATE [dbo].[Foo] 
	SET
		[LastUpdate] = @LastUpdate,
        [Active] = @Active,
        [OtherFlag] = @OtherFlag,
        [FKFirstNotNull] = @FKFirstNotNull,
        [FKSecondNull] = @FKSecondNull,
        [FKThirdDefaultValue] = @FKThirdDefaultValue,
        [Labels] = @Labels	
	WHERE
		[Id] = @Id	
    
	END
